### PR TITLE
midproject

### PR DESCRIPTION
**Pull request by sabnisshreyas91**
I'd love feeback on:
src/config.py - configuration file
src/helper.py - defines functions that are called in run.py
src/run.py - downloads data from public s3 bucket, loads it to configurable private bucket and creates RDS schema in either sqlite or RDS based on config.py

### CODE REVIEW

**Comment by carsonzchen** [comment]
Overall:
- I like that you provided a handle for setting up either a local sqlite database or AWS RDS. 
- Very good instructions on how to configure S3/RDS
- Able to run smoothly and reproduce results
- run.py is sort of a blackbox, it should print some feedback so that I can see that the code did what it intended, specifically:
- the name of the database schema in RDS I just created. It took me a while to find it
- the path of the S3 bucket I uploaded to

**Comment by carsonzchen** [comment]
src/helper.py:
- Fantastic use of try-catch and logger. Code is easy to follow.
- Need to add docstrings to 'create_schema' function.
- I think it might be a little confusing to me to see all these functions in helper.py - my understanding is that helper.py saves commonly used functions (for example, if you have a special way of calculating weighed averages for your data set and it's needed for multiple scripts, you write a weighted_mean function in helper so that it can be imported by different modules). This confuses me with another file in folder (helpers/helpers.py). Maybe consider rename it to data_processing or something similar?

**Comment by carsonzchen** [comment]
run.py
- No problem with this file. Just a suggestion: BUCKET_NAME and BUCKET_FOLDER is something that changes more frequently by the user than those RDS configurations. Instead of manually changing these in the config file, it might be more desirable to make it as a user input using argparse.

**Comment by sabnisshreyas91** [comment]
Thank you for your valuable feedback! 
See summary of changes implemented below:
1) Renamed src/helpers.py to src/data_ingest_schema_create.py
2) There were logger messages indicating what destination S3 bucket the data is being uploaded to and the name of the  RDS database, but you were right in that they were drowned in other messages, I added newlines around the important messages and they seem to be more visible now
3) Added docstring for create_db function within src/data_ingest_schema_create.py which was previously missing
4) Edited run.py to take in optional arguments for bucket name and bucket folder. This was a great suggestion. The values in config.py now server as the default values for the bucket name and bucket folder.

Thanks again for the review!

**Comment by carsonzchen** [comment]
> Thank you for your valuable feedback!
> See summary of changes implemented below:
> 
> 1. Renamed src/helpers.py to src/data_ingest_schema_create.py
> 2. There were logger messages indicating what destination S3 bucket the data is being uploaded to and the name of the  RDS database, but you were right in that they were drowned in other messages, I added newlines around the important messages and they seem to be more visible now
> 3. Added docstring for create_db function within src/data_ingest_schema_create.py which was previously missing
> 4. Edited run.py to take in optional arguments for bucket name and bucket folder. This was a great suggestion. The values in config.py now server as the default values for the bucket name and bucket folder.
> 
> Thanks again for the review!

I can run all the updates now and they look good!

**Pull request merged**
